[[redirects]]
  from = "/api/*"
  to = "https://melo-experience-platform.netlify.app/:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[headers]]
  for = "/api/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"