[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Credentials = "true"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,OPTIONS,PATCH,DELETE,POST,PUT"